name = "Entegre Client"
author = "Tzesh"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b931fc893fe2bbbf29869160efc2b75e0f3cd282c36b828c9fca9ff6165fdf8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
