name = "Entegre Client"
author = "Tzesh"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dcf3fe41f5b99246833504b24be185972a5019da1bff7d6dd91419994040800"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
