name = "Entegre Client"
author = "Tzesh"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cdd14601a795871cf7b5edf95b4dbc07914c4f432c2cdee9ba686841185a8ea"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
